services:
  tech-estate:
    image: nginx:1.27-alpine
    container_name: tech-estate
    ports:
      - "8090:80"
    volumes:
      - ./index.html:/usr/share/nginx/html/index.html:ro
      - ./cave.jpeg:/usr/share/nginx/html/cave.jpeg:ro
    restart: unless-stopped
